[tool.poetry]
name = "finance bot"
version = "1.0.0"
description = "Bot for investing"
authors = ["Kristina Fomina", "Alexey Kryuchkov", "Ilya Isko"]

[tool.poetry.dependencies]
python = "3.9.4"
python-dotenv = "0.19.0"
python-telegram-bot = "13.7"